### ISSUE TITLE
Unable to activate wifi

### ISSUE THREAD

**Issue by Xetius** [drkameleon/WiFiRadar-Pro#1]
Getting the message Wifi Deactivated.

When I try to activate in the menu, I get the following entry in Console

04/09/2015 19:32:04.605 WiFiRadar Pro[957]: Array
(
    [0] => en1 is not a Wi-Fi interface.
    [1] => Turning on the only airport interface found: en0
)

**Comment by higherterrain** [comment]
Same problem. Bought it though BundleHunt

**Comment by skeptikos** [comment]
Same problem.

**Comment by Xetius** [comment]
Is this being investigated?  Reported over a month ago.

**Comment by drkameleon** [comment]
Guys, apologies for the wait (for some reason, I never got notified about the messages here :S)

Could you please all let me know a few things regarding your setup:
- OSX Version?
- Current network interface (you can easily see this by alt-right-clicking onto the default OSX wifi icon)? Is it `en0`, `en1` or sth else?
- Any other issues aside from the "WiFi Deactivated" message?

**Comment by skeptikos** [comment]
Here is some info for you:

Log message:
10/18/15 14:53:19.087 WiFiRadar Pro[795]: Array
(
    [0] => en1 is not a Wi-Fi interface.
    [1] => Turning on the only airport interface found: en0
)

And en0 is the current airport interface.

From System Information:

System Software Overview:
  System Version:   OS X 10.10.5 (14F27)
  Kernel Version:   Darwin 14.5.0
  Boot Mode:    Normal
  Secure Virtual Memory:    Enabled

Hardware Overview:
  Model Name:   MacBook Pro
  Model Identifier: MacBookPro10,1
  Processor Name:   Intel Core i7
  Processor Speed:  2.7 GHz
  Number of Processors: 1
  Total Number of Cores:    4
  L2 Cache (per Core):  256 KB
  L3 Cache: 6 MB
  Memory:   16 GB
  Boot ROM Version: MBP101.00EE.B09
  SMC Version (system): 2.3f35

Wi-Fi:
  Type: AirPort
  Hardware: AirPort
  BSD Device Name:  en0
  IPv4 Addresses:   192.168.1.8
  IPv4:
  AdditionalRoutes:
  DestinationAddress:   192.168.1.8
  SubnetMask:   255.255.255.255
  Addresses:    192.168.1.8
  ARPResolvedIPAddress: 192.168.1.1
  Configuration Method: DHCP
  ConfirmedInterfaceName:   en0
  Interface Name:   en0
  Network Signature:    IPv4.Router=192.168.1.1;IPv4.RouterHardwareAddress=
  Router:   192.168.1.1
  Subnet Masks: 255.255.255.0
  IPv6:
  Configuration Method: Automatic
  DNS:
  Domain Name:  home
  Server Addresses: 192.168.1.1
  DHCP Server Responses:
  Domain Name:  home
  Domain Name Servers:  192.168.1.1
  Lease Duration (seconds): 0
  DHCP Message Type:    0x05
  Routers:  192.168.1.1
  Server Identifier:    192.168.1.1
  Subnet Mask:  255.255.255.0

**Comment by higherterrain** [comment]
I gave up and deleted it.

**Comment by ghost** [comment]
Same issue

Operating System - Mac OS 10.11 - El Capitan
Interface - en0
Did the install and the WiFiRadar Pro window opened with the Wifi deactivated message 

# WiFi Radar messages from Console:

10/19/15 4:37:07.353 PM WiFiRadar Pro[25374]: -[AppDelegate awakeFromNib]
10/19/15 4:37:07.458 PM WiFiRadar Pro[25374]: -[AppDelegate applicationDidFinishLaunching:]
10/19/15 4:37:07.477 PM WiFiRadar Pro[25374]: -[AppDelegate awakeFromNib]
10/19/15 4:37:07.490 PM WiFiRadar Pro[25374]: Product Activated
10/19/15 4:37:07.491 PM WiFiRadar Pro[25374]: Days Remaining: 0
10/19/15 4:37:07.492 PM WiFiRadar Pro[25374]: Product Activated: YES
10/19/15 4:37:07.492 PM WiFiRadar Pro[25374]: License Email: robb@robbperry.com
10/19/15 4:37:07.492 PM WiFiRadar Pro[25374]: License S/N: AD8B3394-B4A946FE-483ACAD4-8D7849FB-3C33904A
10/19/15 4:37:11.479 PM spindump[712]: Saved hang report for WiFiRadar Pro version 2.1 (768) to /Library/Logs/DiagnosticReports/WiFiRadar Pro_2015-10-19-163711_robbs-mbp.hang
10/19/15 4:37:12.336 PM WiFiRadar Pro[25374]: CoreAnimation: warning, deleted thread with uncommitted CATransaction; set CA_DEBUG_TRANSACTIONS=1 in environment to log backtraces.

I attempted to attach the hang report, but do not have permission to attach a .txt file. It is too big to include inline. I am happy to email it, if given an address.

Thanks,

Robb

**Comment by Xetius** [comment]
My OS X version was 10.10.  Now 10.11 (latest version) and still giving the problem.  Only interface is en0

**Comment by drkameleon** [comment]
Well, at last - after your very useful feedback - I believe I've spotted the bug (and it has to do with the one thing all of your reports have in common: a `en0` interface, instead of `en1`.

So... just give me some time, and I'll have it fixed asap. I don't think it'll take more than a few days.

Stay tuned - and, again, thanks for your valuable input! ;-)

**Comment by dcaravana** [comment]
Ping!

**Comment by Xetius** [comment]
Over 2 months and still no update.  Please keep the people paying you money informed...  It is still not working. If this is that hard to fix, I don't have a lot of faith in the rest of the code.

**Comment by drkameleon** [comment]
@Xetius I can understand the frustration, but trust me when I'm saying it's something that it hard to fix, it _is_. What I'm looking for is something that will actually work for everyone (and that's the hard part), and not just throw... a fix just to show I'm doing something.

Believe me, having anyone unhappy with any of my apps is not what I want - that's why I've always refunded anyone who - for this or any other app for that matter - is unsatisfied with something not working...

**Comment by johnhentity** [comment]
I have just installed the app (trial) for the first time, and am geting this same issue.
I would greatly appreciate an update asap - but for now I will for an alternative.
I would be very happy to try again if you get a fix.

**Comment by fereous** [comment]
Got the app via Bundlehunt back in October, installed it today, got same issue as the other posters.

[edit]: Tried the obvious and did a restart (d'oh). Wifiradar works fine now.

**Comment by vedmant** [comment]
The same for me, WiFi deactivated always. App is useless.

**Comment by drkameleon** [comment]
Thanks a lot for all your patience.

As of the upcoming 2.2. (It will be released within a couple of hours) the issue has been fixed. :)
