### ISSUE TITLE
os 10.13 no network found

### ISSUE THREAD

**Issue by tjopke72** [drkameleon/WiFiRadar-Pro#6]
Is wifiradar 10.13 compatible?
Cant find any network anymore.

**Comment by drkameleon** [comment]
Hmm... so it was working up to 10.12 and broke with the latest OS update?

**Comment by tjopke72** [comment]
indeed yes.
It keeps scanning in 10.13

**Comment by drkameleon** [comment]
Doesn't sound good.

Could you please open the Terminal and send me back the result of the 2 following commands?

`/usr/sbin/networksetup -getinfo Wi-Fi`

`/System/Library/PrivateFrameworks/Apple80211.framework/Versions/A/Resources/airport -s -x`

**Comment by tjopke72** [comment]
Last login: Wed Nov  1 11:07:06 on console
MacBook-Pro-A-A:~ aandriessen$ /usr/sbin/networksetup -getinfo Wi-Fi
DHCP Configuration
IP address: 17.77.33.162
Subnet mask: 255.255.255.128
Router: 17.77.33.129
Client ID: 
IPv6: Automatic
IPv6 IP address: none
IPv6 Router: none
Wi-Fi ID: a0:99:9b:0d:9e:4d
MacBook-Pro-A-A:~ aandriessen$

**Comment by tjopke72** [comment]
mailed the other result

**Comment by drkameleon** [comment]
Thanks a lot.

The funny thing is... the results are more than fine. So, in theory, it should be working flawlessly...

I really don't get it. Was there any error message in the Console log?

**Comment by drkameleon** [comment]
P.S. As a sidenote, I myself am running High Sierra (10.13), but haven't noticed any difference with the previous one. I mean... the networks are there...

![screen shot 2017-11-01 at 12 00 00 pm](https://user-images.githubusercontent.com/1265028/32271889-3abf88a6-befc-11e7-8d1a-ad78c19aeea4.png)

**Comment by tjopke72** [comment]
Well can try to remove and re install the app also first then

**Comment by tjopke72** [comment]
Ehh thats funny
Now it works, can be the amount of networks?
Arjan

**Comment by drkameleon** [comment]
Hmmm... That's getting even more weird.

So, it worked without re-installing, re-booting, anything?

P.S. No, the number of networks shoulnd't be an issue whatsoever...

**Comment by tjopke72** [comment]
Yes, close the application, wanted to remove it, but double clicked instead of right click and there it was :)

**Comment by drkameleon** [comment]
Haha. Ok, that's something! :)

**Comment by tjopke72** [comment]
Am at a demo at the apple store in Amsterdam now :)
